name = "peer"
main = "worker.js"
compatibility_date = "2026-05-24"

# חיבור למסד הנתונים
[[d1_databases]]
binding = "DB"
database_name = "peer" # שנה לשם מסד הנתונים שיצרת
database_id = "97c88e7f-b302-4c92-a19e-aefc48813678" # יש להעתיק מדאשבורד קלאודפלייר
